config/routes.rb
Radon::Application.routes.draw do

  resources :announcements

  root to: "pages#show", :name => 'home'
#  root to: "samples#index", constraints: lambda { |r| Page.where(:name => "home").blank? }, as: :samples_root

  resources :prmats

  resources :locations
  
  get '/locations/search', :to => 'locations#search'

  get '/simple_captcha/:action' => 'simple_captcha#index', :as => :simple_captcha
  resources :pages, :except => "show" do
    collection do
      post :sort
    end
  end

  get 'pages/:name' => 'pages#show'
  resources :comments
  resources :literatures_samples
  resources :searches do
    collection do
  post :edit_multiple
  end
  
  
  end

  resources :rights do
    collection do
  post :sort
  end
  
  end
  
#  get '/mapping/search', :to => 'mapping#search'
  
  resources :roles
  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
#  match '/' => 'pages#show', :name => 'home' unless Page.where(:name => "home").blank?
#  match '/' => 'samples#index'
  resources :user_sessions
  resources :users
  resources :dating_methods do
    collection do
  post :sort
  end
  
  
  end

  resources :prmats do
    collection do
  post :sort
  end
  
  
  end

  resources :feature_types do
    collection do
  post :sort
  end
  
  
  end

  resources :literatures do
   collection do
     get :autocomplete
     get :without_bibtex
   end
   get :un_api
   get :un_api, on: :collection
  end

  resources :countries do
    collection do
      post :sort
    end
  end

  resources :country_subdivisions do
    collection do
      post :get_country_subdivisions_by_country
      post :sort
    end
  end

  resources :sites do
    collection do
  post :get_sites_by_country_subdivision
  get :without_geolocalisation
  post :sort
  get :with_geolocalisation
  end
  
  
  end

  resources :labs do
    collection do
  post :sort
  end
  
  
  end

  resources :samples do
    collection do
     get :calibrate_multi
     get :calibrate
     get :calibrate_sum
     post :export_chart
  end
  
  
  end

  resources :samples do
  
    member do
  post :auto_complete_for_site_name
  end
      resources :sites do
        collection do
    get :site
    end
    
    
    end
  end

  resources :phases do
    collection do
  post :get_phases_by_culture
  post :sort
  end
  
  
  end

  resources :cultures do
    collection do
  post :sort
  end
  
  
  end

#  match '/:controller(/:action(/:id))'
end

app/models/country_subdivision.rb
class CountrySubdivision < ActiveRecord::Base
  attr_accessible :name, :country_id

  belongs_to :country
  has_many :sites

  acts_as_list

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :country_id
end

app/controllers/country_subdivisions_controller.rb
class CountrySubdivisionsController < ApplicationController

  filter_access_to :index, :show, :edit, :new, :create, :update, :destroy 

  def get_country_subdivisions_by_country
    @country_subdivisions=CountrySubdivision.where(:country_id => params[:country_id]) unless params[:country_id].blank?
  end
  
  def index
    @country_subdivisions = CountrySubdivision.all
    @country_subdivisions_grid = initialize_grid(CountrySubdivision.with_permissions_to(:show),
    :name => 'country_subdivisions',
    :include => [{:sites => :samples}, :country],
    :enable_export_to_csv => false,
    :csv_file_name => 'countries'
    )
    export_grid_if_requested
  end

  def sort
    if (defined? current_user.roles) && (current_user.roles.map(&:name).detect {|role| role == "admin"}) 
      params[:country_subdivision].each_with_index do |id, index|
        CountrySubdivision.update_all(['position=?', index+1], ['id=?', id])
      end
    end
    render :nothing => true
  end
  
  def show
    @country_subdivision = CountrySubdivision.find(params[:id])
  end
  
  def new
    @country_subdivision = CountrySubdivision.new
  end
  
  def create
    @country_subdivision = CountrySubdivision.new(params[:country_subdivision])
    if @country_subdivision.save
      flash[:notice] = "Successfully created country subdivision."
      redirect_to @country_subdivision
    else
      render :action => 'new'
    end
  end
  
  def edit
    @country_subdivision = CountrySubdivision.find(params[:id])
  end
  
  def update
    @country_subdivision = CountrySubdivision.find(params[:id])
    if @country_subdivision.update_attributes(params[:country_subdivision])
      flash[:notice] = "Successfully updated country subdivision."
      redirect_to @country_subdivision
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @country_subdivision = CountrySubdivision.find(params[:id])
    @country_subdivision.destroy
    flash[:notice] = "Successfully destroyed country subdivision."
    redirect_to country_subdivisions_url
  end
end

app/views/country_subdivisions/_country_subdivision_fields.html.erb
    <%= f.input :name %>
    <%= f.input :country unless (f.object_name.include? "country[") %>

app/views/country_subdivisions/_form.html.erb
<%= semantic_form_for @country_subdivision do |f| %>
  <%= f.inputs do %>
    <%= render "country_subdivision_fields", :f => f %>
  <% end -%>
  <%= f.actions %>
<% end %>

app/views/country_subdivisions/_list_columns.html.erb
<%= grid(@country_subdivisions_grid, :show_filters => :when_filtered) do |g|

  g.row_attributes do |country_subdivision|
    {id: "country_subdivision_" + country_subdivision.id.to_s}
  end

  g.column  :name => 'Name', :attribute => 'name' do |object|
    object.name
  end

  g.column  :name => 'Country', assoc: :country, :attribute => 'name' do |object|
    object.country.name if object.country
  end

  g.column  :name => '14C dates' do |object|

  link_to Sample.includes(:site=>:country_subdivision).with_permissions_to(:show).where(country_subdivisions: {id: object.id}).count, samples_path(:scope => {"country_subdivisions.id"=>object.id} )
  end

  g.column do |object|
    index_table_links(object).html_safe
  end
  
end -%>

app/views/country_subdivisions/_list_detail.html.erb
    <td><%=h table_object.name %></td>
    <td><%=h table_object.country.name rescue nil %></td>

app/views/country_subdivisions/_list_header.html.erb
    <th>Name</th>
    <th>Country</th>

app/views/country_subdivisions/edit.html.erb
<% title "Edit Country Subdivision" %>

<%= render :partial => 'form' %>

<p>
  <%= edit_view_links(@country_subdivision) -%>
</p>

app/views/country_subdivisions/get_country_subdivisions_by_country.js.erb
<% for country_subdivision in @country_subdivisions %>
    <option value="<%= country_subdivision.id %>"><%= country_subdivision.name %></option>
<% end if @country_subdivisions%>

app/views/country_subdivisions/index.html.erb
<%= render :partial => "layouts/standard_list_form2",
  :locals =>
  {
    :model_name => "CountrySubdivision",
    :human_name => "Country Subdivisions",
    :dnd => true
  } %>

app/views/country_subdivisions/new.html.erb
<% title "New Country Subdivision" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", country_subdivisions_path %></p>

app/views/country_subdivisions/show.html.erb
<%- model_class = CountrySubdivision -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize%>: <%=@country_subdivision.name%> </h1>
</div>

<dl class="dl">
  <dt><%= model_class.human_attribute_name(:country) %>:</dt>
  <dd><%= @country_subdivision.country.name rescue nil %></dd>
  <hr>
  <dt>Sites:</dt>
  <dd>
  <ul class="list-unstyled">
    <% unless @country_subdivision.sites.blank? -%>
      <%# @country_subdivision.sites.sort! { |a,b| a.name <=> b.name }.each do |site| 
-%>
      <% @country_subdivision.sites.order(:name).each do |site| -%>

        <li>
          <%= link_to site.name, site -%>
        </li>
      <% end -%> 
    <% else -%>
      none
    <% end -%>
  </ul>
  </dd>
</dl>

<p>
  <%= link_to "Show all dates for " + @country_subdivision.name, samples_path(:scope => {"country_subdivisions.id"=>@country_subdivision.id} ) %>
</p>

<p>
  <%= show_view_links(@country_subdivision) %>
</p>