config/routes.rb
Radon::Application.routes.draw do

  resources :announcements

  root to: "pages#show", :name => 'home'
#  root to: "samples#index", constraints: lambda { |r| Page.where(:name => "home").blank? }, as: :samples_root

  resources :prmats

  resources :locations
  
  get '/locations/search', :to => 'locations#search'

  get '/simple_captcha/:action' => 'simple_captcha#index', :as => :simple_captcha
  resources :pages, :except => "show" do
    collection do
      post :sort
    end
  end

  get 'pages/:name' => 'pages#show'
  resources :comments
  resources :literatures_samples
  resources :searches do
    collection do
  post :edit_multiple
  end
  
  
  end

  resources :rights do
    collection do
  post :sort
  end
  
  end
  
#  get '/mapping/search', :to => 'mapping#search'
  
  resources :roles
  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
#  match '/' => 'pages#show', :name => 'home' unless Page.where(:name => "home").blank?
#  match '/' => 'samples#index'
  resources :user_sessions
  resources :users
  resources :dating_methods do
    collection do
  post :sort
  end
  
  
  end

  resources :prmats do
    collection do
  post :sort
  end
  
  
  end

  resources :feature_types do
    collection do
  post :sort
  end
  
  
  end

  resources :literatures do
   collection do
     get :autocomplete
     get :without_bibtex
   end
   get :un_api
   get :un_api, on: :collection
  end

  resources :countries do
    collection do
      post :sort
    end
  end

  resources :country_subdivisions do
    collection do
      post :get_country_subdivisions_by_country
      post :sort
    end
  end

  resources :sites do
    collection do
  post :get_sites_by_country_subdivision
  get :without_geolocalisation
  post :sort
  get :with_geolocalisation
  end
  
  
  end

  resources :labs do
    collection do
  post :sort
  end
  
  
  end

  resources :samples do
    collection do
     get :calibrate_multi
     get :calibrate
     get :calibrate_sum
     post :export_chart
  end
  
  
  end

  resources :samples do
  
    member do
  post :auto_complete_for_site_name
  end
      resources :sites do
        collection do
    get :site
    end
    
    
    end
  end

  resources :phases do
    collection do
  post :get_phases_by_culture
  post :sort
  end
  
  
  end

  resources :cultures do
    collection do
  post :sort
  end
  
  
  end

#  match '/:controller(/:action(/:id))'
end

app/models/sample.rb
module ActiveRecord
  class Base
    def self.german_float_setters(*syms)
      syms.each do |sym|
      define_method("#{sym}=") do |value|
          if value.class == String
            write_attribute(sym, value.tr(',','.'))
          else
            write_attribute(sym,value)
          end
        end
      end
    end
  end
end

class Sample < ActiveRecord::Base
  attr_accessible :lab_id, :lab_nr, :bp, :std, :delta_13_c, :delta_13_c_std, :prmat_id, :prmat_comment, :comment, :feature, :feature_type_id, :phase_id, :site_id, :approved, :right_id, :dating_method_id, :contact_e_mail, :creator_ip, :site_attributes, :literatures_attributes, :literatures_samples_attributes
  
  german_float_setters :delta_13_c, :delta_13_c_std

  belongs_to :phase
  belongs_to :site
  belongs_to :feature_type
  belongs_to :dating_method
  belongs_to :prmat
  belongs_to :lab
  belongs_to :right
  has_many :comments

  has_many :literatures_samples
  accepts_nested_attributes_for :literatures_samples, :allow_destroy => true

  has_many :literatures, :through => :literatures_samples
  accepts_nested_attributes_for :literatures, :allow_destroy => :false

  validates_presence_of :lab_nr, :bp, :std, :prmat, :feature_type, :right, :site, :phase, :lab
#FIXME  validates_unity_of :lab_nr, :scope => :lab_id

  has_one :culture, :through => :phase

#  accepts_nested_attributes_for :literatures


  accepts_nested_attributes_for :site


  HUMANIZED_ATTRIBUTES = {
    :prmat => "Sample Material",
    :prmat_comment => "Sample Material Comment",
    :lab => "Laboratory",
    :lab_nr => "Sample Number",
    :bp => 'Uncalibrated date',
    :std => 'Standard deviation',
    :delta_13_c => 'Delta 13C value',
    :delta_13_c_std => 'Delta 13C standard deviation',
    :contact_e_mail => 'Contact Email Address'
  }
  
  ATTRIBUTES_HINT_TEXT = {
    :prmat => "The material of the sample",
    :prmat_comment => "Use this field if you want to give additional informations about the sample material",
    :feature => "Enter here the detailed description of the feature (eg. Grave 17)",
    :lab => "Choose the abbreviation of the Laboratory (KIA for Kiel Accelerator)",
    :lab_nr => "Enter the number of the Sample (eg. KIA-2456 => 2456)",
    :bp => "Enter here the uncalibrated date bp",
    :std => 'Enter here standard deviation of the uncalibrated date in years',
    :contact_e_mail => 'Enter here your Email address for clarification requests (will not be shown at the website)'
  }

  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  
  def self.hint_text(attr)
    ATTRIBUTES_HINT_TEXT[attr.to_sym] || nil
  end


  
  def name
    (lab.lab_code rescue "") + "-" + lab_nr
  end
  
#  def self.find_all_by_name(search_name)
#    temps = Sample.all
#    temps.find_all {|temp| logger.debug temp.name.to_yaml
#                            temp.name.include? search_name}
#  end
  
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  include ApplicationHelper

  filter_access_to :new, :create, :edit, :update, :destroy, :calibrate_multi, :export_chart, :calibrate_sum
  filter_access_to :show, :show, :calibrate, :attribute_check => true

#  filter_resource_access

  def index
    safe_scopes = %w(countries.id cultures.id phases.id feature_types.id labs.id literatures.id prmats.id sites.id country_subdivisions.id)
    scope=[]
    
    scope_hash=params[:scope]
    if scope_hash
      scope_hash.delete_if {|k,v| ! safe_scopes.include?(k) }
      scope=[scope_hash.keys.map{|k| "#{k} = ?" }.join(" AND "), scope_hash.values].flatten
    end
     
    if params[:bbox]

      bbox=params[:bbox].split(',')
      
      old_scope_head = scope[0] + ' AND ' if scope_hash
      
      if scope[0] then scope[0]= old_scope_head + 'sites.lat >= ? AND sites.lat <= ? AND sites.lng >= ? AND sites.lng <= ?' end
      scope.push('sites.lat >= ? AND sites.lat <= ? AND sites.lng >= ? AND sites.lng <= ?') if !scope[0]
      
      scope.push(bbox[1].to_f,bbox[3].to_f,bbox[0].to_f,bbox[2].to_f)
    end

    #@samples = Sample.with_permissions_to(:show).paginate :page => params[:page], :per_page => 20, :order => params[:sort]

    @samples_grid = initialize_grid(Sample.with_permissions_to(:show),
    :include => [:lab, :prmat, :feature_type, {:site=>{:country_subdivision => :country}}, {:phase => :culture}, :literatures],
    :name => 'samples',
    :conditions=>scope,
    :enable_export_to_csv => true,
    :csv_field_separator => ';'#,
#    :csv_file_name => 'samples'
    )
    export_grid_if_requested
    
@map='<script defer="defer" type="text/javascript">'

@map << 'var map;'

@map << 'map = new OpenLayers.Map("map", {theme : false,projection : "new OpenLayers.Projection(\"EPSG:900913\")",displayProjection : "new OpenLayers.Projection(\"EPSG:4326\")"});'

      @map << '
              var proj = new OpenLayers.Projection("EPSG:4326");'


      @map << '
            OpenLayers.Feature.Vector.style["default"]["strokeWidth"] = "2";

            var cursors = ["sw-resize", "s-resize", "se-resize",
                "e-resize", "ne-resize", "n-resize", "nw-resize", "w-resize"];
            var context = {
                getCursor: function(feature){
                    var i = OpenLayers.Util.indexOf(controls["transform"].handles, feature);
                    var cursor = "inherit";
                    if(i !== -1) {
                        i = (i + 8 + Math.round(controls["transform"].rotation / 90) * 2) % 8;
                        cursor = cursors[i];
                    }
                    return cursor;
                }
            };
            
            // a nice style for the transformation box
            var style = new OpenLayers.Style({
                cursor: "${getCursor}",
                pointRadius: 5,
                fillColor: "white",
                fillOpacity: 1,
                strokeColor: "black"
            }, {context: context});

            var renderer = OpenLayers.Util.getParameters(window.location.href).renderer;
            renderer = (renderer) ? [renderer] : OpenLayers.Layer.Vector.prototype.renderers;

            var vectors = new OpenLayers.Layer.Vector("Simple Geometry", {
                styleMap: new OpenLayers.StyleMap({
                    "transform": style
                })
            });
            var osm = new OpenLayers.Layer.OSM();

            map.addLayers([osm, vectors]);
                var       controls = {
                regular: new OpenLayers.Control.DrawFeature(vectors,
                            OpenLayers.Handler.RegularPolygon,
                            {handlerOptions: {sides: 4, irregular:true}})
            };
            
            for(var key in controls) {
                map.addControl(controls[key]);
            };
            
            controls.regular.handler.irregular = true;
            
            controls["transform"] = new OpenLayers.Control.TransformFeature(vectors, {
                renderIntent: "transform",
                irregular: true
            });
            
            function addedBox() {
            controls["regular"].deactivate();
            controls["transform"].setFeature(vectors.features[0]);
            controls["transform"].activate();
            }
            
            vectors.events.on({"featureadded": addedBox});
            
            map.addControl(controls["transform"]);

            var button1 = new OpenLayers.Control.Button ({trigger: function() {vectors.removeFeatures(vectors.features);controls["regular"].activate();controls["transform"].deactivate();}, title: "Draw Selection Frame", text: "Draw Selection Frame"});

            var button2 = new OpenLayers.Control.Button ({trigger: function() {var customer_url = "' + url_for(params.merge(:bbox => "nil")) + '";
  customer_url = customer_url.replace("nil",encodeURIComponent(vectors.features[0].geometry.bounds.transform(map.getProjectionObject(),proj)));
  window.location = customer_url;
  }, title: "Enable filter", text: "Enable filter"});
            panel = new OpenLayers.Control.Panel({defaultControl: button1, createControlMarkup: function(control) {
            var button = $("<button class=\'btn btn-info btn-xs\'  style=\'margin-top: 5px;margin-left: 5px;\'>")[0],
                iconSpan = document.createElement("span"),
                textSpan = document.createElement("span");
            iconSpan.innerHTML = "&nbsp;";
            button.appendChild(iconSpan);
            if (control.text) {
                textSpan.innerHTML = control.text;
            }
            button.appendChild(textSpan);
            return button;
        }, class: "btn-group"
});
            panel.addControls([button1,button2]);
            map.addControl (panel);
            '
            @map << 'map.setCenter(new OpenLayers.LonLat(7, 48.9).transform(proj,map.getProjectionObject()), 5);
                     setTimeout(function () {map.setBaseLayer(ghyb);}, 1000);'
            
          if params[:bbox]

            @map << "
            var p1 = new OpenLayers.Geometry.Point(#{bbox[0]},#{bbox[1]}).transform(proj,map.getProjectionObject());
            var p2 = new OpenLayers.Geometry.Point(#{bbox[0]},#{bbox[3]}).transform(proj,map.getProjectionObject());
            var p3 = new OpenLayers.Geometry.Point(#{bbox[2]},#{bbox[3]}).transform(proj,map.getProjectionObject());
            var p4 = new OpenLayers.Geometry.Point(#{bbox[2]},#{bbox[1]}).transform(proj,map.getProjectionObject());
         
            var points = [];
            points.push(p1);
            points.push(p2);
            points.push(p3);
            points.push(p4);
         
            // create a polygon feature from a list of points
            var linearRing = new OpenLayers.Geometry.LinearRing(points);

            
            var polygonFeature = new OpenLayers.Feature.Vector(linearRing, null);

            vectors.addFeatures([polygonFeature]);
            
            map.zoomToExtent(vectors.getDataExtent());
            "
          end
@map << '</script>'
#    end          
  end
  
  def show
    @sample = Sample.find(params[:id])
  end
  
  def new
    @sample = Sample.new
    @sample.build_site
  end
  
  def create
    @sample = Sample.new(params[:sample])
    unless params[:hidden_site_id].blank?
      @sample.site = Site.find(params[:hidden_site_id])
      params[:sample] = params[:sample].except(:site_attributes)
#      params[:sample][:site_id] = params[:hidden_site_id]
    end
#    set_site
    if params[:commit]=="Search"
      @location_proposals = Site.propose_locations(params[:search]).fetch(:geonames,[])
      site_locations= Site.where( "lower(sites.name) LIKE ?", "%#{params[:search].downcase}%").includes(country_subdivision: :country)
      @locations_from_sites = site_locations
      render :action => 'new'       
    elsif @sample.save
      flash[:notice] = "Successfully created sample."
      redirect_to @sample
      session[:users_last_site]=@sample.site
    else
      @sample = Sample.new(params[:sample])
      render :action => 'new'
    end
  end
  
  def edit
    @sample = Sample.find(params[:id])
    @location_proposals=[]
    @locations_from_sites = [@sample.site]
  end
  
  def update
    @sample = Sample.find(params[:id])
    unless params[:hidden_site_id].blank?
      @sample.site = Site.find(params[:hidden_site_id])
      params[:sample] = params[:sample].except(:site_attributes)
#      params[:sample][:site_id] = params[:hidden_site_id]
    end
#    set_site
    if params[:commit]=="Search"
      @location_proposals = Site.propose_locations(params[:search])["geonames"]
      site_locations= Site.where( "lower(sites.name) LIKE ?", "%#{params[:search].downcase}%").includes(country_subdivision: :country)
      @locations_from_sites = site_locations
      render :action => 'edit'       
    elsif @sample.update_attributes(params[:sample])
      flash[:notice] = "Successfully updated sample."
      redirect_to @sample
      session[:users_last_site]=@sample.site
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy
    flash[:notice] = "Successfully destroyed sample."
    redirect_to samples_url
  end
  
  def calibrate
    @sample = Sample.with_permissions_to(:show).find(params[:id])
    out="Options(){RawData=TRUE};Plot(){R_Date(\"#{@sample.name}\",#{@sample.bp},#{@sample.std});};"
    File.open('tmp/radon_calib.oxcal', 'w') {|f| f.write(out) }
    `vendor/oxcal/OxCalLinux tmp/radon_calib.oxcal`
    @log = File.read('tmp/radon_calib.log')
    @graph = File.read('tmp/radon_calib.js')
    @log=@log.split("\n")[6..-1].join("\n")
    result_lines=@log.scan(/\n/).length
    @result_lines=result_lines
    likelihood_start = @graph[/(likelihood.start=)(.*)(;)/,2].to_f
#    @likelihood_start=Time.local(likelihood_start,1,1)

app/views/samples/_fields.html.erb
    <% field_disabling=field_disabling|=false -%>
    <%= f.input :lab, :hint => Sample.hint_text(:lab), :input_html => {:disabled => field_disabling}, :collection => Lab.all.map { |lab| [lab.lab_code + " ("+lab.name+")", lab.id] }.sort %>
    <%= f.input :lab_nr, :hint => Sample.hint_text(:lab_nr), :input_html => {:disabled => field_disabling}  %>
    <hr style = "clear:both;" />
    <%= f.input :bp, :input_html => {:disabled => field_disabling}, :hint => Sample.hint_text(:bp)  %>
    <%= f.input :std, :input_html => {:disabled => field_disabling}  %>
    <%= f.input :delta_13_c, :input_html => {:disabled => field_disabling}  %>
    <%= f.input :delta_13_c_std, :input_html => {:disabled => field_disabling}  %>
    <hr style = "clear:both;" />
    <%= f.input :prmat, :hint => Sample.hint_text(:prmat), :input_html => {:disabled => field_disabling}  %>
    <%= f.input :prmat_comment, :hint => Sample.hint_text(:prmat_comment), :input_html => { :cols => 25, :rows => 4, :disabled => field_disabling }%>
    <hr style = "clear:both;" />
    <%= f.input :feature_type, :input_html => {:disabled => field_disabling}  %>
    <%= f.input :feature, :input_html => {:disabled => field_disabling} , :hint => Sample.hint_text(:feature) %>
    <br style = "clear:both;" />
    <%= label "site", "Site (required)" -%>
    Site associated in the Data Base: <span id="site_display_name"><%= ((@sample && @sample.site) ? @sample.site.name : nil ) || params[:site_name] || 'Not Set'%></span>

    <% if session[:users_last_site] -%>
      <%#= link_to "Use last Site", "#", :'data-function'=> 'use_last_site', :'data_site_id' =>session[:users_last_site]['id'],:'data_site_name' =>session[:users_last_site]['name']  %>
    <% end -%>

    <%= f.semantic_errors :site %>
    <hr style = "clear:both;" />
    <%= f.semantic_fields_for :site do |h| %>
      <%= render :partial => 'sites/fields', :locals => {:f => h} %>
    <% end %>
    <%= hidden_field_tag :hidden_site_id, value = params[:hidden_site_id] %>
		<%#= f.input :hidden_site_id, :as=>:hidden %>

    <hr style = "clear:both;" />
    <%= label "culture", "Culture (required)" -%>
    <% culture_select = nil -%>
    <% unless (f.object==nil) || (f.object.phase==nil) -%>
      <% unless f.object.phase.culture_id.blank? -%>
        <% culture_select = f.object.phase.culture_id -%>
      <% end -%>
    <% end -%>
    <div class="select input required form-group" id="sample_culture_input">
    <label class="  control-label" for="sample_culture_id">Culture</label>
    <span class="form-wrapper">
    <%= select_tag "sample_culture_id", ("<option value = ''>k.A.</option>" + options_from_collection_for_select(Culture.all, 'id', 'name', culture_select.to_i)).html_safe, class: "form-control"%>
    </span>
    </div>
    <%if f.semantic_errors :phase%>
      <p class="inline-errors">Please select Culture and Phase</p>
    <%end%>
    <%= f.input :phase, :as => :select, :collection => option_groups_from_collection_for_select(Culture.order(:name), :phases, :name, :id, :name, f.object.phase ? f.object.phase.id : {} ) %>

	<%= hidden_field_tag 'phases_cache' %>

    <hr style ="clear:both;">
    <% if (permitted_to? :edit, :literatures_samples) && !(f.object_name.include? "literatures_samples") -%>
      <%= f.semantic_fields_for :literatures_samples do |builder| %>
          <%= render "literatures_samples/literatures_sample_fields", :f => builder %>
      <% end %>
    <% end %>
    <p>
    <% if (permitted_to? :new, :literatures_samples)  && !(f.object_name.include? "literature") -%>  
      <%= link_to_add_fields "Add Literature", f, :literatures_samples %>
    <% end -%>


    </p>
    <hr style ="clear:both;">
    <%= f.input :comment,      :input_html => { :cols => 25, :rows => 4,:disabled => field_disabling } %>
    <% if f.object.new_record? -%>
      <% f.object.creator_ip = request.remote_ip -%>
      <%= f.input :creator_ip, :as => :hidden %>
      <%= f.input :contact_e_mail, :hint => Sample.hint_text(:contact_e_mail) %>
    <% end -%>
    <%= f.input :right, :input_html => {:disabled => field_disabling} %>
    <% if ((current_user) && (current_user.login == "admin")) -%>
   	<%= f.input :approved,  :as => :radio, :input_html => {:disabled => field_disabling}  %>
	 <% end -%>

app/views/samples/_form.html.erb
<%= semantic_form_for @sample do |f| %>
  <%= f.inputs "Sample" do %>
      <%= render "fields", :f => f %>
    <% end -%>
    <%= f.actions do %>
      <%= f.action :submit, :as => :button, label: 'Submit' , :button_html => { :class => 'btn btn-primary'} %>
    <% end %>
<% end %>

app/views/samples/_list_detail.html.erb
      <td><%=h table_object.lab.lab_code rescue nil %></td>
      <td><%=h table_object.lab_nr %></td>
      <td><%=h table_object.bp %></td>
      <td><%=h table_object.std %></td>
      <td><%=h table_object.delta_13_c %></td>
      <td><%=h table_object.delta_13_c_std %></td>
      <td><%=h table_object.prmat.name rescue nil %></td>
      <td><%=h table_object.comment %></td>
      <td><%=h table_object.feature %></td>
      <td><%=h table_object.feature_type.name rescue nil %></td>
      <td><%=h table_object.phase.culture.name rescue nil %></td>
      <td><%=h table_object.phase.name rescue nil %></td>
      <td><%=h table_object.site.name rescue nil %></td>

app/views/samples/_list_header.html.erb
    <th><%= Sample.human_attribute_name(:lab)[0..2] -%>.</th>
    <th><%= Sample.human_attribute_name(:lab_nr) -%></th>
    <th>Bp</th>
    <th>Std</th>
    <th>Delta 13 C</th>
    <th>Delta 13 C Std</th>
    <th><%= Sample.human_attribute_name(:prmat) -%></th>
    <th><%= Sample.human_attribute_name(:comment) -%></th>
    <th>Feature</th>
    <th>Feature Type</th>
    <th>Culture</th>
    <th>Phase</th>
    <th>Site</th>
    <th></th>

app/views/samples/_samples_grid.html.erb
  <%= grid(@samples_grid, :show_filters => :when_filtered) do |g|

    g.row_attributes do |sample|
      {id: "sample_" + sample.id.to_s}
    end

    g.action_column :param_name => :handle_multiple, :html => {:class => 'handle_multiple'}, :object_property => :id

  
    g.column  :name => 'ID', :attribute => 'id' do |sample|
      sample.id
    end

    g.column :name => 'Lab Code', assoc: :lab, :attribute => 'lab_code' do |sample|
      sample.lab.lab_code  if sample.lab
    end
    
    g.column :name => 'Lab Nr.', :attribute => 'lab_nr' do |sample|
      sample.lab_nr
    end

    g.column :name => 'BP', :attribute => 'bp' do |sample|
      sample.bp
    end
    
    g.column :name => 'Std', :attribute => 'std' do |sample|
      sample.std
    end
    
    g.column :name => 'δ 13C', :attribute => 'delta_13_c' do |sample|
      sample.delta_13_c
    end
    
    g.column  :name => 'Sample Mat.', assoc: :prmat, :attribute => 'name'  do |sample|
      sample.prmat.name if sample.prmat
    end

    g.column  :name => 'Feature Type', assoc: :feature_type, :attribute => 'name'  do |sample|
      sample.feature_type.name if sample.feature_type
    end
    
    g.column  :name => 'Culture', assoc: :culture, :attribute => 'name'  do |sample|
      sample.culture.name if sample.culture
    end

    g.column  :name => 'Phase', assoc: :phase, :attribute => 'name'  do |sample|
      sample.phase.name if sample.phase
    end
    
    g.column  :name => 'Site', assoc: :site, :attribute => 'name'  do |sample|
      sample.site.name if sample.site
    end
    
    g.column  :name => 'Lat', assoc: :site, :attribute => 'lat', :in_html => false  do |sample|
      sample.site.lat if sample.site
    end
    
    g.column  :name => 'Lng', assoc: :site, :attribute => 'lng', :in_html => false  do |sample|
      sample.site.lng if sample.site
    end

    g.column  :name => 'literature', assoc: :literatures, :attribute => 'long_citation', :in_html => false  do |sample|
      sample.literatures.collect(&:long_citation).join("; ") unless sample.literatures.blank?
    end
   
    g.column :in_csv => false do |sample|
      index_table_links(sample).html_safe
    end
  end
  %>

app/views/samples/edit.html.erb
<%- model_class = Sample -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/samples/new.html.erb
<%- model_class = Sample -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/samples/show.html.erb
<% present @sample do |sample_presenter| %>

  <%- model_class = Sample -%>
    <div class="page-header">
      <h1><%=sample_presenter.title%> </h1>
    </div>
  </div>
    </div>
  <div class="row-fluid">
  <div class="col-md-6">
  <p>
    <strong>Laboratory:</strong>
    <%= sample_presenter.lab_name  %>
  </p>
  <hr>
  <p>
    <strong>BP:</strong> <%= sample_presenter.bp %>
    <strong>Std:</strong> <%= sample_presenter.std %>
  </p>
  <p>
    <strong><%= Sample.human_attribute_name(:delta_13_c) %></strong>
    <%= sample_presenter.delta_13_c %>
    <strong><%= Sample.human_attribute_name(:delta_13_c_std) %></strong>
    <%= sample_presenter.delta_13_c_std %>
  </p>
  <p>
    <strong><%= Sample.human_attribute_name(:prmat) %>:</strong>
    <%= sample_presenter.prmat_name  %>
    <strong><%= Sample.human_attribute_name(:prmat_comment) %>:</strong>
    <%= sample_presenter.prmat_comment %>
  </p>
  <p>
    <strong>Feature Type:</strong>
    <%= sample_presenter.feature_type_name %>
    <strong>Feature:</strong>
    <%= sample_presenter.feature %>
  </p>
  <p>
    <strong>Culture:</strong>
    <%= sample_presenter.culture_name  %>
    <strong>Phase:</strong>
    <%= sample_presenter.phase_name  %>
  </p>
  <hr>
  <p>
    <strong>Site:</strong>
    <%= sample_presenter.linked_site  %>
    <strong>Country Subdivision:</strong>
    <%=h @sample.site.country_subdivision.name rescue nil %>
    <strong>Country:</strong>
    <%=h @sample.site.country_subdivision.country.name rescue nil %>
  </p>
  <hr>
  <p>
    <strong>Approved:</strong>
    <%=h @sample.approved %>
    <strong>Right:</strong>
    <%=h @sample.right.name rescue nil %>
  </p>
  <hr>
  <% unless @sample.literatures.blank? -%>
    <p>
      <strong>Literature:</strong>
      <% @sample.literatures.each do |literature| -%>
        <p>
          <% link_title = (literature.long_citation rescue "no citation given") unless literature.long_citation.blank? -%>
          <%=link_to link_title || "no citation given", literature %>

          <link rel="unapi-server" type="application/xml" href="<%= literature_un_api_path(literature, :format => :xml) %>"/>

          <abbr class='unapi-id' title='<%=literature.id%>'/>
        </p>
      <% end -%>  
    </p>
  <% end -%>
  <hr>
  <p>
    <strong>Comment:</strong>
    <%=h @sample.comment %>
  </p>
  <hr>
  <p>
    <strong>User Comments:</strong>
    <% unless @sample.comments.blank? -%>
      <% @sample.comments.each do |comment| -%>
        <p><%=h comment.comment %> -- <%= comment.user.login rescue "Guest" -%>
        </p>
        <%= if permitted_to? :edit, :comments then link_to "Edit", edit_comment_path(comment) end -%>
        <%= if permitted_to? :destroy, :comments then link_to "Destroy", comment, :confirm => 'Are you sure?', :method => :delete end-%>
      <% end -%>
    <% end -%>
  </p>
  </div>
  <div class="col-md-6">
    <%= sample_presenter.map %>
  </div>
  </div>
  <div class="row">
    <div class="col-md-5">
      <div class="form-actions well">

      <% if permitted_to? :new, :comments -%>
          <%= semantic_form_for :comment, :url => comments_path do |builder| %>
          <% builder.object = Comment.new -%>
            <%= builder.inputs "Add User Comment" do %>
              <%= builder.input :comment, :input_html => {:cols => '50', :rows => "5"} %>
              <%= builder.input :user_id, as: :hidden, :input_html => { value: current_user ? current_user.id : nil }%>
              <%= builder.input :sample_id, as: :hidden, :input_html => { value: @sample.id }%>
              <%= recaptcha_tags %>
            <%= builder.actions do %>
              <%= builder.action :submit, :as => :button, :button_html => { class: "btn btn-primary" } %>
              <%= builder.action :cancel, :as => :link, :button_html => { class: "btn btn-default" }  %>
            <% end %>
            <% end -%>

          <% end %>
      <% end -%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= show_view_links(@sample) %>
    </div>
  </div>
<% end -%>