config/routes.rb
Radon::Application.routes.draw do

  resources :announcements

  root to: "pages#show", :name => 'home'
#  root to: "samples#index", constraints: lambda { |r| Page.where(:name => "home").blank? }, as: :samples_root

  resources :prmats

  resources :locations
  
  get '/locations/search', :to => 'locations#search'

  get '/simple_captcha/:action' => 'simple_captcha#index', :as => :simple_captcha
  resources :pages, :except => "show" do
    collection do
      post :sort
    end
  end

  get 'pages/:name' => 'pages#show'
  resources :comments
  resources :literatures_samples
  resources :searches do
    collection do
  post :edit_multiple
  end
  
  
  end

  resources :rights do
    collection do
  post :sort
  end
  
  end
  
#  get '/mapping/search', :to => 'mapping#search'
  
  resources :roles
  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
#  match '/' => 'pages#show', :name => 'home' unless Page.where(:name => "home").blank?
#  match '/' => 'samples#index'
  resources :user_sessions
  resources :users
  resources :dating_methods do
    collection do
  post :sort
  end
  
  
  end

  resources :prmats do
    collection do
  post :sort
  end
  
  
  end

  resources :feature_types do
    collection do
  post :sort
  end
  
  
  end

  resources :literatures do
   collection do
     get :autocomplete
     get :without_bibtex
   end
   get :un_api
   get :un_api, on: :collection
  end

  resources :countries do
    collection do
      post :sort
    end
  end

  resources :country_subdivisions do
    collection do
      post :get_country_subdivisions_by_country
      post :sort
    end
  end

  resources :sites do
    collection do
  post :get_sites_by_country_subdivision
  get :without_geolocalisation
  post :sort
  get :with_geolocalisation
  end
  
  
  end

  resources :labs do
    collection do
  post :sort
  end
  
  
  end

  resources :samples do
    collection do
     get :calibrate_multi
     get :calibrate
     get :calibrate_sum
     post :export_chart
  end
  
  
  end

  resources :samples do
  
    member do
  post :auto_complete_for_site_name
  end
      resources :sites do
        collection do
    get :site
    end
    
    
    end
  end

  resources :phases do
    collection do
  post :get_phases_by_culture
  post :sort
  end
  
  
  end

  resources :cultures do
    collection do
  post :sort
  end
  
  
  end

#  match '/:controller(/:action(/:id))'
end

app/models/right.rb
class Right < ActiveRecord::Base
  attr_accessible :name, :id

  has_many :samples

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/rights_controller.rb
class RightsController < ApplicationController

  filter_access_to :index, :show, :edit, :new, :create, :update, :destroy 

  def index
    @rights = Right.order("position ASC").all
  end

  def sort
    if (defined? current_user.roles) && (current_user.roles.map(&:name).detect {|role| role == "admin"}) 
      params[:rights].each_with_index do |id, index|
        Right.update_all(['position=?', index+1], ['id=?', id])
      end
    end
    render :nothing => true
  end
  
  def show
    @right = Right.find(params[:id])
  end
  
  def new
    @right = Right.new
  end
  
  def create
    @right = Right.new(params[:right])
    if @right.save
      flash[:notice] = "Successfully created right."
      redirect_to @right
    else
      render :action => 'new'
    end
  end
  
  def edit
    @right = Right.find(params[:id])
  end
  
  def update
    @right = Right.find(params[:id])
    if @right.update_attributes(params[:right])
      flash[:notice] = "Successfully updated right."
      redirect_to @right
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @right = Right.find(params[:id])
    @right.destroy
    flash[:notice] = "Successfully destroyed right."
    redirect_to rights_url
  end
end

app/views/rights/_form.html.erb
<%= semantic_form_for @right do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end -%>
  <%= f.actions %>
<% end %>

app/views/rights/_list_detail.html.erb
      <td><%=h table_object.name %></td>

app/views/rights/_list_header.html.erb
    <th>Name</th>

app/views/rights/edit.html.erb
<% title "Edit Right" %>

<%= render :partial => 'form' %>

<p>
  <%= edit_view_links(@right) -%>
</p>

app/views/rights/index.html.erb
<%= render :partial => "layouts/standard_list_form",
  :locals =>
  {
    :model_name => "Right",
    :human_name =>  "Rights",
    :dnd => true
  } %>

app/views/rights/new.html.erb
<% title "New Right" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", rights_path %></p>

app/views/rights/show.html.erb
<% title "Right" %>

<p>
  <strong>Name:</strong>
  <%=h @right.name %>
</p>

<p>
  <%= link_to "Show all dates for " + @right.name, search_path(:params => {"combine_option"=>"and", "commit"=>"Search", "action"=>"show", "search_0.samples.right_id.id"=>@right.id, "haupttabelle_id"=>"samples", "controller"=>"searches",  "operator_0.samples.right_id.id"=>"="}) %>
</p>

<p>
  <%= show_view_links(@right) %>
</p>