config/routes.rb
Radon::Application.routes.draw do

  resources :announcements

  root to: "pages#show", :name => 'home'
#  root to: "samples#index", constraints: lambda { |r| Page.where(:name => "home").blank? }, as: :samples_root

  resources :prmats

  resources :locations
  
  get '/locations/search', :to => 'locations#search'

  get '/simple_captcha/:action' => 'simple_captcha#index', :as => :simple_captcha
  resources :pages, :except => "show" do
    collection do
      post :sort
    end
  end

  get 'pages/:name' => 'pages#show'
  resources :comments
  resources :literatures_samples
  resources :searches do
    collection do
  post :edit_multiple
  end
  
  
  end

  resources :rights do
    collection do
  post :sort
  end
  
  end
  
#  get '/mapping/search', :to => 'mapping#search'
  
  resources :roles
  get 'signup' => 'users#new', :as => :signup
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
#  match '/' => 'pages#show', :name => 'home' unless Page.where(:name => "home").blank?
#  match '/' => 'samples#index'
  resources :user_sessions
  resources :users
  resources :dating_methods do
    collection do
  post :sort
  end
  
  
  end

  resources :prmats do
    collection do
  post :sort
  end
  
  
  end

  resources :feature_types do
    collection do
  post :sort
  end
  
  
  end

  resources :literatures do
   collection do
     get :autocomplete
     get :without_bibtex
   end
   get :un_api
   get :un_api, on: :collection
  end

  resources :countries do
    collection do
      post :sort
    end
  end

  resources :country_subdivisions do
    collection do
      post :get_country_subdivisions_by_country
      post :sort
    end
  end

  resources :sites do
    collection do
  post :get_sites_by_country_subdivision
  get :without_geolocalisation
  post :sort
  get :with_geolocalisation
  end
  
  
  end

  resources :labs do
    collection do
  post :sort
  end
  
  
  end

  resources :samples do
    collection do
     get :calibrate_multi
     get :calibrate
     get :calibrate_sum
     post :export_chart
  end
  
  
  end

  resources :samples do
  
    member do
  post :auto_complete_for_site_name
  end
      resources :sites do
        collection do
    get :site
    end
    
    
    end
  end

  resources :phases do
    collection do
  post :get_phases_by_culture
  post :sort
  end
  
  
  end

  resources :cultures do
    collection do
  post :sort
  end
  
  
  end

#  match '/:controller(/:action(/:id))'
end

app/models/search.rb
class Search

  attr_reader :keyword
  
  def self.find(param)
    all.detect { |search| search.to_param == param } || raise(ActiveRecord::RecordNotFound)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
#require 'will_paginate/array'
  def index

    do_search
    if (params[:show_all]=='true') then @end_result = @end_result_all end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  #{ render :xml => @gefaesseinheits_all }
#      format.csv  { render :csv => @end_result }      
      format.csv  { download_csv}
      format.oxcal
    end
  end


  # GET /searches/1
  # GET /searches/1.xml
  def show

    redirect_to params.merge!(:action => :index, :specified_fields=>{"lab.name".to_sym =>"lab.name", :bp => "bp", :lab_nr => "lab_nr", :std => "std"})

#    do_search
#    
#    respond_to do |format|
#      format.html # show.html.erb
#      format.xml  { render :xml => @end_result }
#    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new
    session[:search_hist]=""

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  def update_subfields

    chain = params[:id].split(".") #Ausgangs-Kette einlesen
    chain_new=[]
    chain_new.push(chain[0]) #Ziel-Kette mit Starttabelle bestücken
    level = 0 #Suchtiefe auf null setzen

    chain[0..-2].each do |link| #Für jedes Glied der Kette
      level=level+1 #Such-Level erhöhen
      assocs=chain_new[level-1].classify.constantize.reflect_on_all_associations #alle Assoziationen für die Tabelle auswerfen
      this_assoc=assocs.detect {|assoc| assoc.primary_key_name==chain[level]} #testen, ob das nächste glied der Kette einer Assoziation entspricht

      this_assoc=this_assoc || assocs.detect {|assoc| assoc.table_name==chain[level]} #FIXME testen, ob das nächste glied der Kette einer hm_Assoziation entspricht
      if this_assoc # Wenn ja
        chain_new.push(this_assoc.association_foreign_key[0..-4]) #wird dieses der neuen Kette hinzugefügt
      else # Sonst
        break # verlasse die Schleife
      end
    end
    table=chain_new.last # Die Tabelle, für die das Auswahlfeld bevölkert werden soll, ist das letzte Glied der neuen Kette
    unless table.blank?
      @update_subfields = table.classify.constantize.column_names.sort #Holt die Spaltennamen der aktuellen Tabelle
      @update_associations = table.classify.constantize.reflect_on_all_associations #holt die Assoziationen der aktuellen Tabelle
      @hm_assocs = table.classify.constantize.reflect_on_all_associations(:has_many)
      @ho_assocs = table.classify.constantize.reflect_on_all_associations(:has_one)
#      @hm_assocs.push(table.classify.constantize.reflect_on_all_associations(:has_one))
      if chain_new.length!=chain.length #Wenn beiden Ketten in Länge differieren (also ein Glied als Nicht-Assoziation erkannt wurde)
        if table==chain.last || chain.last =="name"
          @update_subfields=table.classify.constantize.all #Hole den Inhalt der Tabelle
        else
          @update_subfields=nil
        end
        @column_type = table.classify.constantize.columns.detect{|column| column.name == chain.last}.type.to_s
        @field_type="input" #Setze Feldtyp als Input-Feld
      end      
    else
      render :nothing => true
    end
  end

=begin #FIXME Edit multiple not activated
  def edit_multiple
    if params[:edit_multiple] == "Markierte Löschen"
      delete_multiple
    else
      @objects = params[:haupttabelle_id].classify.constantize.find(params[:object_ids])
      object_controller = eval(params[:haupttabelle_id].camelize + "Controller").new
      object_controller.send('collect_instances')

      instance_variables = object_controller.instance_variable_names

      instance_variables.each do |instance_variable|
        instance_variable_set(instance_variable, object_controller.instance_variable_get(instance_variable))
      end
    end
  end
  
  def update_multiple
    @objects = params[:haupttabelle_id].classify.constantize.find(params[:object_ids])
    param_prefix = (params[:haupttabelle_id].classify.underscore)

    @objects.each do |object|
      object.update_attributes(params[param_prefix.to_sym].reject { |k,v| v.blank? })
    end
    flash[:notice] = params[:haupttabelle_id].classify.humanize + ": Datensätze mit den ID " + params[:object_ids].join(", ") + " wurden ver&auml;ndert!"
    redirect_to params[:referrer]
  end
=end
  
  protected
  
    def download_csv
    @performed_render = false
    
    do_search
    
#    require 'fastercsv' 
    require 'iconv'
    fields_to_show = [
    "id",
    ]
    
    if params[:haupttabelle_id] == "samples"
      out='Options(){RawData=TRUE};Plot(){'
      @end_result_all.each do |sample|
        out<<"R_Date('#{sample.id}',#{sample.bp},#{sample.std});"
      end
      out<<'};'
      File.open('tmp/radon_calib.oxcal', 'w') {|f| f.write(out) }
      `vendor/oxcal/OxCalLinux tmp/radon_calib.oxcal`
      oxcal_out = File.read('tmp/radon_calib.txt')
      oxcal_out = oxcal_out.split("\n")
      one_sigma=Array.new
      one_sigma[0]='One Sigma'
      two_sigma=Array.new
      two_sigma[0]='Two Sigma'
      oxcal_out.each do |calib_result|
        unless calib_result.blank?
          calib_result = calib_result.split(' ')
          if (calib_result.length < 5)
            calib_result = ['na','na','na','na','na']
          end
          one_sigma.push(calib_result[1]+" (68.2%) "+calib_result[2])
          two_sigma.push(calib_result[3]+" (95.4%) "+calib_result[4])
        end
      end
      user_files_mask = File.join("#{Rails.root}/tmp/radon_calib*")

      user_files = Dir.glob(user_files_mask)

      user_files.each do |file_location|
        File.delete(file_location)
      end
    end


    temp_file = Tempfile.new(Digest::MD5.hexdigest(rand(12).to_s))
    temp_path = temp_file.path()
    content_columns = []
    params[:haupttabelle_id].classify.constantize.content_columns.each do |column|
      if column.type.to_s=="float"
        content_columns << "replace(to_char(#{params[:haupttabelle_id]}.#{column.name},'9999D999'),'.',',') AS #{column.name}"
      else
        content_columns << "#{params[:haupttabelle_id]}.#{column.name}"
      end
    end

    sql_select = "COPY (SELECT #{params[:haupttabelle_id]}.id, " + content_columns.join(", ") + " "

    sql_from = "FROM #{params[:haupttabelle_id]} "
    sql_where = "WHERE #{params[:haupttabelle_id]}.id IN ('" + @end_result_all.map(&:id).join("', '") + "')"
    sql_end = ")TO STDOUT DELIMITER ';' CSV HEADER;"

    assocs=params[:haupttabelle_id].classify.constantize.reflect_on_all_associations(:belongs_to)
    assocs_join =[]
    assocs_select = []
    assocs.each do |assoc|
      assoc_colums = assoc.class_name.classify.constantize.column_names
      assoc_field = nil
      if assoc_colums.detect{|e| e=="name"}
        assoc_field = "name"
      elsif assoc_colums.detect{|e| e==assoc.class_name.tableize.singularize}
        assoc_field = assoc.class_name.tableize.singularize
      else
        next
      end
      unless assoc_field.blank?
        assoc_select = assoc.name.to_s.tableize + "." + assoc_field + " AS " + assoc.name.to_s
        assoc_join = "LEFT JOIN " + assoc.class_name.tableize.to_s + " AS " + assoc.name.to_s.tableize + " ON " + params[:haupttabelle_id] + "." + assoc.primary_key_name + " =" + assoc.name.to_s.tableize + ".id"
        assocs_select << assoc_select
        assocs_join << assoc_join
      end

    end
    
    if params[:haupttabelle_id] == "samples"
      assocs_select.push("cultures.name AS culture")
      assocs_select.push("labs.lab_code AS lab_code")
      assocs_select.push("sites.lat AS lat")
      assocs_select.push("sites.lng AS lng")
      assocs_join.push("LEFT JOIN cultures on phases.culture_id=cultures.id")
    end


    
    sql = sql_select + ", " + assocs_select.join(", ") + " " + sql_from + " " + assocs_join.join(" ") + " "  + sql_where + sql_end
    
    conn = ActiveRecord::Base.connection_pool.checkout
    pg_conn = conn.raw_connection
    pg_conn.exec("#{sql}")

    csv = String.new()
    index=-1
    begin
      while line = pg_conn.get_copy_data
        index = index + 1
        logger.debug line
        if params[:haupttabelle_id] == "samples"
          line = line.strip + ';' + one_sigma[index] + ';' + two_sigma[index]
        end
        temp_file.write Iconv.conv('ISO-8859-15//TRANSLIT//IGNORE', 'utf-8', line) + "\n"
      end
    rescue
      ActiveRecord::Base.connection_pool.checkin(conn)
    ensure
      ActiveRecord::Base.connection_pool.checkin(conn)
    end

  temp_file.close

  send_file temp_file.path, :type => 'text/csv; charset=ISO-8859-1; header=present', :filename => "#{params[:haupttabelle_id]}.csv"   
  end

=begin function delete_multiple not activated
  def delete_multiple
    @objects = params[:haupttabelle_id].classify.constantize.find(params[:object_ids])
    @objects.each do |object|
      object.destroy
    end
  flash[:notice] = "Markierte gel&ouml;scht!"
  redirect_to :back
  end
=end


  def do_search

    @end_result = []
    if params[:simple_search] == "1"
      temp_results=[]
      search_op = []
      4.times do |index|
        search_value = params[("simple_value_"+index.to_s).to_sym]
        unless search_value.blank?
          search = params[("simple_search_"+index.to_s).to_sym]
          search_op.push(params[("simple_operator_"+(index).to_s).to_sym])

          search_field = case search
               when "country"  then "site.country_subdivision.countries.name"
               when "culture"   then "phase.culture.name"
               when "literatures" then "literatures.map(&:long_citation).join(' ')"
               when "rights"  then "rights.name"
               when "country_subdivisions"   then "site.country_subdivision.name"
               when "labs" then "lab.name"
               when "prmats" then "prmat.name"
               when "dating_methods" then "dating_method.name"
               when "sites" then "site.name"
               when "feature_types" then "feature_type.name"

app/views/searches/_search_list_specify_fields.html.erb
<style>
        body { font-size: 62.5%; }
        label, input { display:block; }
        input.text { margin-bottom:12px; width:95%; padding: .4em; }
        fieldset { padding:0; border:0; margin-top:25px; }
        h1 { font-size: 1.2em; margin: .6em 0; }
        div#users-contain { width: 350px; margin: 20px 0; }
        div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
        div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
        .ui-dialog .ui-state-error { padding: .3em; }
        .validateTips { border: 1px solid transparent; padding: 0.3em; }
    </style>

<% not_to_show = ["id", "created_at", "updated_at", "position"] -%>
<script>
    $(function() {
        $( "#specify_fields" ).dialog({
            modal: true,
            autoOpen: false,
            buttons: {
                Ok: function() {
                    $( this ).dialog( "close" );
                },
                Cancel: function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    $("#toggle_visible_fields_link")
            .button()
            .click(function() {
                $( "#specify_fields" ).dialog( "open" );
            });
    });
    </script>
<% current_user_role_names = current_user.roles.map(&:name) rescue [] -%>
    <div id="specify_fields" class="popup" >
<%= form_tag searches_path, :method => 'get' do %>
    <%#= link_to_function "Show/Hide",  "$('specify_fields').toggle()"  %>
    <hr>
      <% params[:haupttabelle_id].classify.constantize.column_names.each do |column| -%>
        <% if (current_user_role_names.detect {|role_name| role_name == "admin" }) || !(not_to_show.detect{|e| e  == column }) -%>
          <% if column.to_s[-3..-1] == "_id"-%>
            <% subclass = params[:haupttabelle_id].classify.constantize.reflect_on_all_associations.detect {|e| e.primary_key_name == column} %>
            <% subtable = subclass.table_name rescue nil -%>
            <% if subtable -%>
              <% name = ((subclass.class_name.constantize.column_names.detect{|e| e == "name"}) ? "name" : nil) -%>
              <% name = ((subclass.class_name.constantize.column_names.detect{|e| e == subclass.class_name.underscore}) ? subclass.class_name.underscore : name)  -%>
            <% end -%>
            <% if name -%>
              <% column = column.gsub("_id","") + "." + name %>
            <% end -%>
          <% end -%>

          <% checked = params[:specified_fields][column.to_sym] rescue false -%>
          <% searches = params.select {|k,v| k[0..6] == "search_"} -%>
          <% searches.each do |search| -%>
            <% if search[0].split(".")[2..-1].join(".").gsub("_id","")==column then checked=true end %>
          <% end -%>

         <div style = "float:left;">
           <%= check_box_tag "specified_fields["+column+"]", column, checked , :style => "display:inline;" %>
           <%= label_tag column, column.split(".").first.gsub("_id","").humanize, :style => "display:inline;" %>
         </div>
        <% end -%>
      <% end -%>
      <%= hash_as_hidden_fields(params.except(:specified_fields)).html_safe %>

      <hr style ="clear:both;">
      <%= submit_tag "Update", :name => nil, :style => "float:right;"-%>
      <button type="button" id="close" onclick='$( "#specify_fields" ).dialog( "close" );'>Cancel</button>
      <%#= tag :input, :type => 'button', :value => 'Cancel', :class => 'popup_closebox' %>
<% end %>
    </div>
<p><button id="toggle_visible_fields_link">toggle visible fields</button></p>

app/views/searches/_search_query.html.erb
<b> search was: </b> 

<% if params[:simple_search] -%>
  <% 4.times do |index| -%>
  <% search_value=params[('simple_value_' + index.to_s ).to_sym] -%>
  <% search_search=params[('simple_search_' + index.to_s ).to_sym] -%>
  <% search_operator=params[('simple_operator_' + index.to_s ).to_sym] || '' -%>
    <% unless (search_value.blank?)  -%>
      <%= search_operator + ' ' + search_search + '=' + search_value %>
    <% end -%>
  <% end -%>
<% else -%>
    <% search_count=-1 -%>
    <% searches = params.select {|k,v| k[0..6] == "search_"} -%>
    <% operators= params.select {|k,v| k[0..8] == "operator_"}-%>
  <% searches.each do |search| -%>
    <% search_count+=1 -%>
    <%= search.to_a[0].split(".")[1..-1].join(".") %> <%= operators.to_a[search_count][1] %> <%= search[1] %> <%= params[:combine_option] unless search_count == searches.length-1 %>
  <% end -%>
<% end -%>

app/views/searches/_search_result_alternatives.html.erb
<% index_params=params.clone -%>
<% show_params=params.clone -%>

<p>
<% unless @end_result.blank? -%>
  <% index_params["action"]="index" -%>
  <% index_params["id"]=nil -%>
  <% show_params["action"]="show" -%>

      <%#= link_to "Results as list", :params => show_params, :show_list => true   Rausgenommen, da Luise sagte, die Liste braucht keiner -%>

      <%= link_to "Results as table", url_for(index_params) -%> |
      <%= link_to "Results as csv", url_for(index_params.merge(:format=>"csv")) -%> |
      <%= link_to "Results for Oxcal", url_for(index_params.merge(:format=>"oxcal")), {:popup => ['oxcal_code', 'height=300,width=600,resizable=yes,scrollbars=yes,status=yes']} -%>    <br/>
<% end -%>
</p>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<% form_for(@search) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/edit_multiple.html.erb
<% form_for :searches, :url => update_multiple_searches_path, :html => { :method => :put } do |f| %>


    <% for object in @objects %>

        <%= hidden_field_tag "object_ids[]", object.id %>

    <% end %>
<div class="flash_warning">
Folgende Datensätze werden Bearbeitet: <%= @objects.map(&:id).join(", ") %>
</div>
  <%= hidden_field_tag "haupttabelle_id", params[:haupttabelle_id] %>
  <%= hidden_field_tag "referrer", request.env['HTTP_REFERER'] %>

  <% object_class = params[:haupttabelle_id].classify.constantize -%>
  <% instance_variable_set "@#{params[:haupttabelle_id].singularize}", object_class.new -%>

  <%= render :partial => "#{params[:haupttabelle_id]}/form", :locals => {:bearbeiten => true, :submit_text => "Senden"} %>

<% end -%>

<%= javascript_tag "
function getElementsAsArray(html_collection){
  var i, tmp = [];
  for(i = 0; i< html_collection.length; i++){
    tmp.push(html_collection[i]);
  }
  return tmp;
}

function secure_checkboxes() {
  $$('input').each(function(e){
    if(e.type == 'checkbox') {
      hiddens = document.getElementsByName(e.name);
      getElementsAsArray(hiddens).each(function(f){
        if(f.type == 'hidden') {
          f.disable();
        };
      });
      var change_button = new Element('input',{
                            'type':'checkbox',
                            'id': e.name + '_change',
                            'style':'display:inline;',
                            'value': e.value});

//      change_button = '<input type=\\'checkbox\\' id=\\''+e.name+'_change\\' style=\\'display:inline;\\' /> &Auml;ndern? ';
      change_element = Element.insert(e, {before: change_button});
      Element.insert(change_button, {after: '&Auml;ndern?'});
      
      //    content = '<input type=\\'radio\\' id=\\''+e.name+'\\' name=\\''+e.name+'\\' value=\\''+e.value+'\\' style=\\'display:inline;\\' /> ja <input type=\\'radio\\' id=\\''+e.name+'\\' name=\\''+e.name+'\\' value=\\'0\\' style=\\'display:inline\\'/> nein <input type=\\'radio\\' id=\\''+e.name+'\\' name=\\''+e.name+'\\' value=\\'\\' checked=\\'checked\\' style=\\'display:inline\\' /> nicht &auml;ndern';

      //    Element.replace(e, content);

      e.disable();
      change_button.observe('click', function(event){toggle_checkboxes (Event.element(event))});

    };
  });
};
Event.observe(window, 'load', function() {secure_checkboxes();});

function toggle_checkboxes (element)
{
  name_of_to_toggle = element.identify().substring(0,element.identify().length-7)
  to_toggle_collection = document.getElementsByName(name_of_to_toggle);
  to_toggle = getElementsAsArray(to_toggle_collection)
  to_toggle.each(function(el){
      if (el.value==element.value)
        {el[el.disabled ? 'enable' : 'disable']();}
  });
}
"
-%>

app/views/searches/index.html.erb
<% searches = params.select {|k,v| k[0..6] == "search_"} -%>
<% column_names = ["Id"] -%>
<% columns = ["id"] -%>
<% searches.each do |search| -%>
    <% column_names.push(search[0].split(".")[2..-2].join(".").gsub("_id","").humanize) %>
    <% columns.push(search[0].split(".")[2..-1].join(".").gsub("_id","")) %>
<% end -%>
<% if params[:specified_fields] -%>
  <% params[:specified_fields].keys.each do |specified_field| -%>
      <% column_names.push(specified_field.split(".").first.to_s.gsub("_id","").humanize) %>
      <% columns.push(specified_field) %>
  <% end -%>
<% end -%>
<div style="text-align:center; float:right;">
<%= link_to 'New Search', new_search_path %> | 
<%= link_to "Show all entries of table #{params[:haupttabelle_id].singularize.humanize}", send("#{params[:haupttabelle_id]}_path") -%>
<hr>
<%= render :partial => "search_result_alternatives" -%>
</div>
<div style="clear:both; float:left;">
<%= render :partial => "search_list_specify_fields" rescue nil %>
</div>
<%# form_tag edit_multiple_searches_path do %>
<%#= hidden_field_tag 'haupttabelle_id', params[:haupttabelle_id] %>
<%= render :partial => "layouts/standard_list_form",
  :locals =>
  {
#    :model_name => "#{params[:haupttabelle_id].classify.constantize.to_s}",
    :model_name => "Search",
    :human_name => "Search in #{params[:haupttabelle_id].singularize.humanize}, results as table",
    :extra_column_names => column_names,
    :extra_columns => columns
  } %>
<%#FIXME function edit_multipe not activated
<#input type="checkbox" id="toggleAll" onclick="$$('input.handle_multiple').each(function(box) { box.checked = $('toggleAll').checked; });" style="display:inline;">
%>
<%#= label_tag 'toggleAll', "Toggle all", :style=>"display:inline;" %>
<%#= submit_tag "delete marked", :name => "edit_multiple", :confirm => 'Are you sure?' %>
<%#= submit_tag "edit marked", :name => "edit_multiple" %>
<%# end -%>
<%= render :partial => "search_query" -%>

<p style="text-align:right;">
<%= link_to 'New Search', new_search_path %> | 
<%= link_to "Show all data from #{params[:haupttabelle_id].singularize.humanize}", send("#{params[:haupttabelle_id]}_path") -%>
</p>

app/views/searches/index.oxcal.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Search Result :: Oxcal Code</title>
</head>
<pre>
/*
The result is formatted for Oxcal input.
If you want to use the dates as model, just uncomment the lines
by deleting the // before the entries.
*/

//Sequence()
//{
//  Boundary("Start");
//  Phase()
//  {
<% @end_result_all.each do |result| %>
    R_Date("<%= result.name.to_s rescue "no_name" -%>", <%= result.bp %>, <%= result.std %>);<% end %>
    
//  };
//  Boundary("End");
//};
</pre>

app/views/searches/show.html.erb
<div style="text-align:center; float:right;">
<%= link_to 'New Search', new_search_path %> | 
<%= link_to "Show all entries of table #{params[:haupttabelle_id].singularize.humanize}", send("#{params[:haupttabelle_id]}_path") -%>
<hr>
<%= render :partial => "search_result_alternatives" -%>
</div>
<h1>Search results</h1>

<p><b>Result:</b> <%= @end_result.total_entries -%> rows<br/>
<%= render :partial => "search_query" -%>
<% unless @end_result.blank? -%>
  <%# if params[:show_list] -%>
    <h2> Results as list </h2>
    Samples with the following IDs met your search:<br/>
    <% @end_result.each do |end_result| -%>
      <%= link_to end_result.id, end_result  %>
      <br/>
    <% end -%>
  <%# end -%>
<% end -%>
</p>
<p>
<%= link_to 'New Search', new_search_path %>
</p>